language: node_js
node_js:
  - "8"

sudo: required

addons:
  chrome: stable

install:
  - npm i
  - npm i -g codecov

script:
  - npm run test
  - codecov

deploy:
- provider: script
  script: set -o pipefail && ./deploy-check.sh $TRAVIS_TAG
  on:
    tags: true
- provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
