pool:
  vmImage: 'ubuntu-latest'

pr:
  branches:
    include:
    - '*'

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
       - '*'

variables:
  - group: global-variables
  - name: BRANCH_NAME
    value: $[variables['Build.SourceBranch']]

jobs:
- job: build
  displayName: 'Build'
  steps:
  - task: Npm@1
    displayName: "Install dependencies"
    inputs:
      command: 'install'

  - task: Npm@1
    displayName: "Build"
    inputs:
      command: 'custom'
      customCommand: 'run build'

  - task: Npm@1
    displayName: "Test"
    inputs:
      command: 'custom'
      customCommand: 'test'

  - script: |
      npm install codecov
      ./node_modules/.bin/codecov
    condition: and(succeeded(), contains(variables['BRANCH_NAME'], 'master'))
    displayName: 'Upload coverage report'
    env:
      CODECOV_TOKEN: $(codecovToken)

  - bash: ./deploy-check.sh $(echo ${BRANCH_NAME/refs\/tags\//})
    condition: and(succeeded(), contains(variables['BRANCH_NAME'], 'refs/tags/'))
    displayName: 'Check package version matches tag'
    failOnStderr: true

  - publish: $(System.DefaultWorkingDirectory)
    condition: and(succeeded(), contains(variables['BRANCH_NAME'], 'refs/tags/'))
    artifact: spi-client-js

# Note that the release pipeline contains the deployment steps to npm
